name: 'lemmaai_analytics'
version: '1.0.0'
config-version: 2

profile: 'lemmaai_analytics'

model-paths: ['models']
clean-targets: ['target', 'dbt_packages']

models:
  lemmaai_analytics:
    marts:
      +materialized: view
