-- ABYSS: PostgreSQL schema based on ABYSS.pdf (42 pages).
-- Fresh database design, NOT an in-place migration of the earlier two tables.
-- Related entity tables are 3NF; vw_/mv_ objects are display-ready data.
-- Read DESIGN.md for REQUIRED command-handler invariants and projection behavior.
-- UUIDs can be supplied by the application; gen_random_uuid() is the fallback.
-- All instants use timestamptz. Handlers maintain updated_at and aggregate versions.
BEGIN;

-- 1. ACCOUNT AND ACCESS
-- Under this section: individual login identities and platform privileges.
CREATE TABLE users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    username VARCHAR(50) NOT NULL CHECK (length(trim(username)) > 0),
    email VARCHAR(254) NOT NULL,
    password_hash TEXT NOT NULL,
    display_name VARCHAR(100),
    status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active','suspended','closed')),
    email_verified_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    version BIGINT NOT NULL DEFAULT 1 CHECK (version > 0)
);
CREATE UNIQUE INDEX users_username_ci ON users (lower(username));
CREATE UNIQUE INDEX users_email_ci ON users (lower(email));
COMMENT ON TABLE users IS '1. Accounts: individual sign-in identities; never share a squad password.';
COMMENT ON COLUMN users.password_hash IS 'Password hash only; never plaintexmvt or reversible encryption.';
CREATE TABLE user_roles (
    user_id UUID NOT NULL REFERENCES users(id),
    role TEXT NOT NULL CHECK (role IN ('representative','moderator','admin')),
    granted_by UUID REFERENCES users(id),
    granted_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, role)
);
COMMENT ON TABLE user_roles IS '1. Platform roles. Guests have no account or guest role row.';
CREATE TABLE auth_tokens (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES users(id),
    purpose TEXT NOT NULL CHECK (purpose IN ('refresh','verify_email','reset_password')),
    token_hash TEXT NOT NULL UNIQUE,
    expires_at TIMESTAMPTZ NOT NULL,
    consumed_at TIMESTAMPTZ,
    revoked_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK (expires_at > created_at)
);
CREATE INDEX auth_tokens_user ON auth_tokens (user_id, purpose);
CREATE INDEX auth_tokens_expiry ON auth_tokens (expires_at);
COMMENT ON TABLE auth_tokens IS '1. Hashed session/reset/verification tokens; consume or rotate atomically.';

-- 2. REFERENCE DATA AND UPLOADED FILES
-- Under this section: editable catalogs. MLBB ranks, squad levels and ABYSS ratings differ.
CREATE TABLE regions (
    code VARCHAR(20) PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    default_timezone TEXT NOT NULL
);
COMMENT ON TABLE regions IS '2. Matchmaking regions and IANA timezone defaults.';
CREATE TABLE game_ranks (
    id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(60) NOT NULL UNIQUE,
    sort_order SMALLINT NOT NULL UNIQUE
);
COMMENT ON TABLE game_ranks IS '2. MLBB rank catalog; seed from an approved list rather than mockup values.';
CREATE TABLE squad_levels (
    code VARCHAR(30) PRIMARY KEY,
    name VARCHAR(60) NOT NULL,
    verification_required BOOLEAN NOT NULL DEFAULT false
);
COMMENT ON TABLE squad_levels IS '2. Squad classification, e.g. Amateur or Collegiate, independent of MLBB rank.';
CREATE TABLE heroes (
    id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(80) NOT NULL UNIQUE,
    is_active BOOLEAN NOT NULL DEFAULT true
);
COMMENT ON TABLE heroes IS '2. Hero catalog for player hero pools; maintained without game API integration.';
CREATE TABLE media_assets (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    uploaded_by UUID NOT NULL REFERENCES users(id),
    object_key TEXT NOT NULL UNIQUE,
    mime_type VARCHAR(100) NOT NULL,
    byte_size BIGINT NOT NULL CHECK (byte_size > 0),
    sha256 CHAR(64),
    access_scope TEXT NOT NULL DEFAULT 'private' CHECK (access_scope IN ('private','public')),
    scan_status TEXT NOT NULL DEFAULT 'pending' CHECK (scan_status IN ('pending','clean','rejected')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
COMMENT ON TABLE media_assets IS '2. Object-storage metadata for avatars, posts and evidence. No binary files or expiring signed URLs in SQL.';

-- 3. SQUAD AND PLAYER PROFILES
-- Under this section: squad identity, representatives, individual players and roster history.
CREATE TABLE squads (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    public_number BIGINT GENERATED ALWAYS AS IDENTITY UNIQUE,
    owner_user_id UUID NOT NULL REFERENCES users(id),
    name VARCHAR(100) NOT NULL CHECK (length(trim(name)) > 0),
    slug VARCHAR(120) NOT NULL UNIQUE,
    acronym VARCHAR(15),
    bio TEXT,
    region_code VARCHAR(20) NOT NULL REFERENCES regions(code),
    timezone TEXT NOT NULL DEFAULT 'Asia/Manila',
    level_code VARCHAR(30) NOT NULL REFERENCES squad_levels(code),
    avatar_asset_id UUID REFERENCES media_assets(id),
    banner_asset_id UUID REFERENCES media_assets(id),
    status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active','suspended','archived')),
    verified_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    version BIGINT NOT NULL DEFAULT 1 CHECK (version > 0),
    CHECK (slug = lower(slug))
);
CREATE INDEX squads_owner ON squads (owner_user_id);
COMMENT ON TABLE squads IS '3. Squad profile: name, acronym, description, level, region and branding. Ownership is separate from coaching authority.';
COMMENT ON COLUMN squads.public_number IS 'Human-friendly ABYSS display ID, not the MLBB squad ID or an authorization secret.';
CREATE TABLE squad_coaches (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    squad_id UUID NOT NULL REFERENCES squads(id),
    user_id UUID NOT NULL REFERENCES users(id),
    coach_role TEXT NOT NULL DEFAULT 'head_coach' CHECK (coach_role IN ('head_coach','assistant_coach')),
    is_primary BOOLEAN NOT NULL DEFAULT false,
    can_manage_roster BOOLEAN NOT NULL DEFAULT true,
    can_manage_scrims BOOLEAN NOT NULL DEFAULT true,
    can_message_opponents BOOLEAN NOT NULL DEFAULT true,
    joined_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    left_at TIMESTAMPTZ,
    CHECK (left_at IS NULL OR left_at >= joined_at),
    UNIQUE (id, user_id, squad_id),
    UNIQUE (id, squad_id)
);
CREATE UNIQUE INDEX squad_coaches_active ON squad_coaches (squad_id, user_id) WHERE left_at IS NULL;
CREATE UNIQUE INDEX squad_coaches_one_primary ON squad_coaches (squad_id) WHERE left_at IS NULL AND is_primary;
CREATE INDEX squad_coaches_user ON squad_coaches (user_id) WHERE left_at IS NULL;
COMMENT ON TABLE squad_coaches IS '3. Coaches are the authorized squad representatives. A primary coach manages the roster, matchmaking and coach-to-coach contact.';
CREATE TABLE players (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    linked_user_id UUID UNIQUE REFERENCES users(id),
    created_by UUID NOT NULL REFERENCES users(id),
    in_game_name VARCHAR(100) NOT NULL,
    real_name VARCHAR(150),
    mlbb_account_id VARCHAR(30) NOT NULL,
    mlbb_zone_id VARCHAR(30) NOT NULL,
    current_rank_id SMALLINT REFERENCES game_ranks(id),
    current_stars INTEGER CHECK (current_stars >= 0),
    highest_rank_id SMALLINT REFERENCES game_ranks(id),
    highest_stars INTEGER CHECK (highest_stars >= 0),
    preferred_role VARCHAR(30),
    avatar_asset_id UUID REFERENCES media_assets(id),
    rank_reported_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    version BIGINT NOT NULL DEFAULT 1 CHECK (version > 0),
    UNIQUE (mlbb_account_id, mlbb_zone_id)
);
COMMENT ON TABLE players IS '3. MLBB player profile, current/highest rank and stars. A roster player need not have an ABYSS login.';
COMMENT ON COLUMN players.real_name IS 'Private optional roster detail; exclude from public projections.';
COMMENT ON COLUMN players.mlbb_zone_id IS 'Game account and zone stored separately as text, preserving identifiers exactly.';
CREATE TABLE player_heroes (
    player_id UUID NOT NULL REFERENCES players(id),
    hero_id SMALLINT NOT NULL REFERENCES heroes(id),
    preference_order SMALLINT NOT NULL CHECK (preference_order > 0),
    PRIMARY KEY (player_id, hero_id),
    UNIQUE (player_id, preference_order)
);
COMMENT ON TABLE player_heroes IS '3. Player hero pool: one row per hero, not comma-separated values.';
CREATE TABLE squad_roster (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    squad_id UUID NOT NULL REFERENCES squads(id),
    player_id UUID NOT NULL REFERENCES players(id),
    added_by_coach_id UUID NOT NULL,
    roster_role TEXT NOT NULL CHECK (roster_role IN ('captain','starter','substitute')),
    joined_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    left_at TIMESTAMPTZ,
    CHECK (left_at IS NULL OR left_at >= joined_at),
    FOREIGN KEY (added_by_coach_id, squad_id) REFERENCES squad_coaches(id, squad_id)
);
CREATE UNIQUE INDEX roster_one_active_squad ON squad_roster (player_id) WHERE left_at IS NULL;
CREATE UNIQUE INDEX roster_one_active_captain ON squad_roster (squad_id) WHERE left_at IS NULL AND roster_role = 'captain';
CREATE INDEX roster_squad ON squad_roster (squad_id, joined_at DESC);
COMMENT ON TABLE squad_roster IS '3. Membership history. A coach registers each player for their squad; no fixed player1/player2 columns.';

-- 4. MATCHMAKING, INVITATIONS AND SCHEDULES
-- Under this section: availability, challenges, accepted matches and negotiated changes.
CREATE TABLE squad_availability (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    squad_id UUID NOT NULL REFERENCES squads(id),
    starts_at TIMESTAMPTZ NOT NULL,
    ends_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK (ends_at > starts_at)
);
CREATE INDEX availability_squad_time ON squad_availability (squad_id, starts_at, ends_at);
COMMENT ON TABLE squad_availability IS '4. Optional concrete availability windows. A later service can expand recurring availability.';
CREATE TABLE scrim_invites (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    sender_squad_id UUID NOT NULL REFERENCES squads(id),
    recipient_squad_id UUID NOT NULL REFERENCES squads(id),
    created_by UUID NOT NULL REFERENCES users(id),
    created_by_coach_id UUID NOT NULL,
    proposed_start TIMESTAMPTZ NOT NULL,
    proposed_end TIMESTAMPTZ NOT NULL,
    series_format TEXT NOT NULL DEFAULT 'best_of' CHECK (series_format IN ('best_of','fixed_games')),
    game_count SMALLINT NOT NULL CHECK (game_count BETWEEN 1 AND 99),
    message TEXT,
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','accepted','declined','cancelled','expired')),
    expires_at TIMESTAMPTZ NOT NULL,
    responded_by UUID REFERENCES users(id),
    responded_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    version BIGINT NOT NULL DEFAULT 1 CHECK (version > 0),
    UNIQUE (id, sender_squad_id, recipient_squad_id),
    FOREIGN KEY (created_by_coach_id, created_by, sender_squad_id)
        REFERENCES squad_coaches(id, user_id, squad_id),
    CHECK (sender_squad_id <> recipient_squad_id),
    CHECK (proposed_end > proposed_start),
    CHECK (expires_at > created_at AND expires_at <= proposed_start),
    CHECK (series_format <> 'best_of' OR game_count % 2 = 1),
    CHECK ((status = 'pending' AND responded_at IS NULL) OR (status <> 'pending' AND responded_at IS NOT NULL))
);
CREATE INDEX invites_inbox ON scrim_invites (recipient_squad_id, status, created_at DESC, id);
CREATE INDEX invites_sent ON scrim_invites (sender_squad_id, status, created_at DESC, id);
CREATE INDEX invites_expiry ON scrim_invites (expires_at) WHERE status = 'pending';
CREATE UNIQUE INDEX invites_pending_pair_slot ON scrim_invites
    (LEAST(sender_squad_id,recipient_squad_id), GREATEST(sender_squad_id,recipient_squad_id), proposed_start)
    WHERE status = 'pending';
COMMENT ON TABLE scrim_invites IS '4. Received and sent invites query the same authoritative invitation.';
CREATE TABLE scrims (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    invite_id UUID NOT NULL UNIQUE,
    home_squad_id UUID NOT NULL REFERENCES squads(id),
    away_squad_id UUID NOT NULL REFERENCES squads(id),
    scheduled_start TIMESTAMPTZ NOT NULL,
    scheduled_end TIMESTAMPTZ NOT NULL,
    series_format TEXT NOT NULL CHECK (series_format IN ('best_of','fixed_games')),
    game_count SMALLINT NOT NULL CHECK (game_count BETWEEN 1 AND 99),
    status TEXT NOT NULL DEFAULT 'scheduled' CHECK (status IN ('scheduled','in_progress','awaiting_result','disputed','completed','cancelled','no_show')),
    actual_start TIMESTAMPTZ,
    actual_end TIMESTAMPTZ,
    cancellation_reason TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    version BIGINT NOT NULL DEFAULT 1 CHECK (version > 0),
    FOREIGN KEY (invite_id, home_squad_id, away_squad_id)
        REFERENCES scrim_invites(id, sender_squad_id, recipient_squad_id),
    CHECK (home_squad_id <> away_squad_id),
    CHECK (scheduled_end > scheduled_start),
    CHECK (actual_end IS NULL OR (actual_start IS NOT NULL AND actual_end >= actual_start)),
    CHECK (series_format <> 'best_of' OR game_count % 2 = 1)
);
CREATE INDEX scrims_home_schedule ON scrims (home_squad_id, scheduled_start, scheduled_end);
CREATE INDEX scrims_away_schedule ON scrims (away_squad_id, scheduled_start, scheduled_end);
COMMENT ON TABLE scrims IS '4. Two squads per series. Handler copies accepted terms atomically and locks both squads to prevent overlaps.';
CREATE TABLE scrim_reschedule_requests (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    scrim_id UUID NOT NULL REFERENCES scrims(id),
    proposed_by_squad_id UUID NOT NULL REFERENCES squads(id),
    created_by UUID NOT NULL REFERENCES users(id),
    expected_scrim_version BIGINT NOT NULL CHECK (expected_scrim_version > 0),
    proposed_start TIMESTAMPTZ NOT NULL,
    proposed_end TIMESTAMPTZ NOT NULL,
    reason TEXT,
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','accepted','declined','cancelled','expired')),
    expires_at TIMESTAMPTZ NOT NULL,
    decided_by UUID REFERENCES users(id),
    decided_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK (proposed_end > proposed_start),
    CHECK (expires_at > created_at),
    CHECK ((status = 'pending' AND decided_at IS NULL) OR (status <> 'pending' AND decided_at IS NOT NULL))
);
CREATE UNIQUE INDEX reschedule_one_pending ON scrim_reschedule_requests (scrim_id) WHERE status = 'pending';
COMMENT ON TABLE scrim_reschedule_requests IS '4. Opposing squad accepts negotiated changes; stale proposals cannot overwrite newer schedules.';
CREATE TABLE scrim_lineups (
    scrim_id UUID NOT NULL REFERENCES scrims(id),
    squad_id UUID NOT NULL REFERENCES squads(id),
    player_id UUID NOT NULL REFERENCES players(id),
    in_game_name_snapshot VARCHAR(100) NOT NULL,
    role_snapshot VARCHAR(30),
    PRIMARY KEY (scrim_id, player_id)
);
COMMENT ON TABLE scrim_lineups IS '4. Historical lineup snapshot; roster transfers cannot rewrite past participation.';

-- 5. RESULTS, SCREENSHOT PROOF, OCR AND RATINGS
-- Under this section: submitted results and human confirmation; OCR is supporting evidence.
CREATE TABLE result_submissions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    scrim_id UUID NOT NULL REFERENCES scrims(id),
    submitted_by_squad_id UUID NOT NULL REFERENCES squads(id),
    submitted_by UUID NOT NULL REFERENCES users(id),
    home_wins SMALLINT NOT NULL CHECK (home_wins >= 0),
    away_wins SMALLINT NOT NULL CHECK (away_wins >= 0),
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','confirmed','disputed','rejected','superseded')),
    reviewed_by UUID REFERENCES users(id),
    reviewed_at TIMESTAMPTZ,
    review_note TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (scrim_id, id)
);
CREATE INDEX results_scrim_time ON result_submissions (scrim_id, created_at DESC);
CREATE UNIQUE INDEX result_one_pending_per_squad ON result_submissions (scrim_id, submitted_by_squad_id) WHERE status = 'pending';
COMMENT ON TABLE result_submissions IS '5. Preserve submitted claims; corrections are new rows. Only approved claims become canonical results.';
CREATE TABLE result_evidence (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    submission_id UUID NOT NULL REFERENCES result_submissions(id),
    asset_id UUID NOT NULL REFERENCES media_assets(id),
    game_number SMALLINT CHECK (game_number > 0),
    ocr_status TEXT NOT NULL DEFAULT 'pending' CHECK (ocr_status IN ('pending','processing','succeeded','failed','not_requested')),
    ocr_extracted JSONB,
    ocr_confidence NUMERIC(5,4) CHECK (ocr_confidence BETWEEN 0 AND 1),
    ocr_model_version TEXT,
    processed_at TIMESTAMPTZ,
    UNIQUE (submission_id, asset_id)
);
COMMENT ON TABLE result_evidence IS '5. Screenshot proof and optional OCR output for moderator logs. OCR success does not establish result validity.';
CREATE TABLE scrim_results (
    scrim_id UUID PRIMARY KEY REFERENCES scrims(id),
    accepted_submission_id UUID NOT NULL UNIQUE,
    home_wins SMALLINT NOT NULL CHECK (home_wins >= 0),
    away_wins SMALLINT NOT NULL CHECK (away_wins >= 0),
    outcome TEXT NOT NULL CHECK (outcome IN ('home_win','away_win','draw','void')),
    finalized_by UUID NOT NULL REFERENCES users(id),
    finalized_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    version BIGINT NOT NULL DEFAULT 1 CHECK (version > 0),
    FOREIGN KEY (scrim_id, accepted_submission_id) REFERENCES result_submissions(scrim_id, id),
    CHECK ((outcome = 'home_win' AND home_wins > away_wins)
        OR (outcome = 'away_win' AND away_wins > home_wins)
        OR (outcome = 'draw' AND home_wins = away_wins) OR outcome = 'void')
);
COMMENT ON TABLE scrim_results IS '5. One canonical series result. FinalizeResult validates accepted claim, scores and series rules.';
CREATE TABLE rating_seasons (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(80) NOT NULL,
    starts_at TIMESTAMPTZ NOT NULL,
    ends_at TIMESTAMPTZ NOT NULL,
    algorithm_version VARCHAR(40) NOT NULL,
    rules JSONB NOT NULL DEFAULT '{}'::jsonb,
    CHECK (ends_at > starts_at)
);
COMMENT ON TABLE rating_seasons IS '5. ABYSS rating periods and versioned rules, independent of official MLBB ranks/seasons.';
CREATE TABLE squad_ratings (
    season_id UUID NOT NULL REFERENCES rating_seasons(id),
    squad_id UUID NOT NULL REFERENCES squads(id),
    rating NUMERIC(12,4) NOT NULL,
    rated_series INTEGER NOT NULL DEFAULT 0 CHECK (rated_series >= 0),
    version BIGINT NOT NULL DEFAULT 1 CHECK (version > 0),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (season_id, squad_id)
);
COMMENT ON TABLE squad_ratings IS '5. Authoritative platform rating for matchmaking, not a client-editable profile field.';
CREATE TABLE rating_changes (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    season_id UUID NOT NULL REFERENCES rating_seasons(id),
    squad_id UUID NOT NULL REFERENCES squads(id),
    scrim_id UUID NOT NULL REFERENCES scrims(id),
    result_version BIGINT NOT NULL CHECK (result_version > 0),
    rating_before NUMERIC(12,4) NOT NULL,
    rating_after NUMERIC(12,4) NOT NULL,
    algorithm_version VARCHAR(40) NOT NULL,
    reason TEXT NOT NULL CHECK (reason IN ('result','correction')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (season_id, squad_id, scrim_id, result_version)
);
COMMENT ON TABLE rating_changes IS '5. Auditable, deduplicated rating effects; corrections require a defined adjustment/recalculation policy.';

-- 6. SOCIAL FEED AND SQUAD MESSAGING
-- Under this section: profile posts, attachments, squad conversations and per-user read state.
CREATE TABLE squad_posts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    squad_id UUID NOT NULL REFERENCES squads(id),
    author_user_id UUID NOT NULL REFERENCES users(id),
    body TEXT NOT NULL DEFAULT '',
    label VARCHAR(80),
    visibility TEXT NOT NULL DEFAULT 'public' CHECK (visibility IN ('public','squad')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ,
    version BIGINT NOT NULL DEFAULT 1 CHECK (version > 0)
);
CREATE INDEX posts_squad_feed ON squad_posts (squad_id, created_at DESC, id) WHERE deleted_at IS NULL;
COMMENT ON TABLE squad_posts IS '6. Home/profile feed posts with optional label and public or squad-only visibility.';
CREATE TABLE post_assets (
    post_id UUID NOT NULL REFERENCES squad_posts(id),
    asset_id UUID NOT NULL REFERENCES media_assets(id),
    sort_order SMALLINT NOT NULL DEFAULT 0 CHECK (sort_order >= 0),
    PRIMARY KEY (post_id, asset_id),
    UNIQUE (post_id, sort_order)
);
COMMENT ON TABLE post_assets IS '6. Ordered post attachments; handler requires text or at least one attachment.';
CREATE TABLE conversations (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    first_squad_id UUID NOT NULL REFERENCES squads(id),
    second_squad_id UUID NOT NULL REFERENCES squads(id),
    next_sequence BIGINT NOT NULL DEFAULT 1 CHECK (next_sequence > 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK (first_squad_id < second_squad_id),
    UNIQUE (first_squad_id, second_squad_id)
);
COMMENT ON TABLE conversations IS '6. One direct conversation per unordered squad pair; UUID ordering canonicalizes the pair.';
CREATE TABLE messages (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    conversation_id UUID NOT NULL REFERENCES conversations(id),
    sequence BIGINT NOT NULL CHECK (sequence > 0),
    sender_user_id UUID NOT NULL REFERENCES users(id),
    sender_squad_id UUID NOT NULL REFERENCES squads(id),
    sender_coach_id UUID NOT NULL,
    body TEXT NOT NULL CHECK (length(trim(body)) BETWEEN 1 AND 10000),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ,
    UNIQUE (conversation_id, sequence),
    FOREIGN KEY (sender_coach_id, sender_user_id, sender_squad_id)
        REFERENCES squad_coaches(id, user_id, squad_id)
);
COMMENT ON TABLE messages IS '6. Coach-to-coach messages. The composite foreign key proves that the sender is a coach of the sending squad.';
CREATE TABLE conversation_reads (
    conversation_id UUID NOT NULL REFERENCES conversations(id),
    user_id UUID NOT NULL REFERENCES users(id),
    last_read_sequence BIGINT NOT NULL DEFAULT 0 CHECK (last_read_sequence >= 0),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (conversation_id, user_id)
);
COMMENT ON TABLE conversation_reads IS '6. Individual read cursor for each authorized representative; advance monotonically.';

-- 7. NOTIFICATIONS
-- Under this section: durable notification intent and per-user read state.
CREATE TABLE notifications (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    recipient_user_id UUID NOT NULL REFERENCES users(id),
    recipient_squad_id UUID REFERENCES squads(id),
    source_event_id UUID NOT NULL,
    kind VARCHAR(80) NOT NULL,
    payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    read_at TIMESTAMPTZ,
    UNIQUE (recipient_user_id, source_event_id, kind)
);
CREATE INDEX notifications_unread ON notifications (recipient_user_id, created_at DESC, id) WHERE read_at IS NULL;
COMMENT ON TABLE notifications IS '7. Durable notification/read state; source-event ID deduplicates retries without FK to the prunable outbox.';

-- 8. FEEDBACK, REPORTS, VERIFICATION AND MODERATION
-- Under this section: manual review, evidence, reasons and accountable decisions.
CREATE TABLE feedback (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    submitted_by UUID NOT NULL REFERENCES users(id),
    squad_id UUID REFERENCES squads(id),
    scrim_id UUID REFERENCES scrims(id),
    category VARCHAR(80) NOT NULL,
    body TEXT NOT NULL CHECK (length(trim(body)) > 0),
    status TEXT NOT NULL DEFAULT 'new' CHECK (status IN ('new','reviewing','resolved','closed')),
    assigned_to UUID REFERENCES users(id),
    response TEXT,
    resolved_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    version BIGINT NOT NULL DEFAULT 1 CHECK (version > 0)
);
CREATE INDEX feedback_queue ON feedback (status, created_at, id);
COMMENT ON TABLE feedback IS '8. Platform feedback and optional scrim feedback; not an automatic disciplinary report.';
CREATE TABLE reports (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    reporter_user_id UUID NOT NULL REFERENCES users(id),
    reporter_squad_id UUID NOT NULL REFERENCES squads(id),
    reported_squad_id UUID NOT NULL REFERENCES squads(id),
    scrim_id UUID REFERENCES scrims(id),
    category VARCHAR(80) NOT NULL,
    description TEXT NOT NULL CHECK (length(trim(description)) > 0),
    status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open','investigating','resolved','dismissed')),
    assigned_to UUID REFERENCES users(id),
    resolved_by UUID REFERENCES users(id),
    resolution TEXT,
    resolved_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    version BIGINT NOT NULL DEFAULT 1 CHECK (version > 0),
    CHECK (reporter_squad_id <> reported_squad_id),
    CHECK ((status IN ('resolved','dismissed') AND resolved_by IS NOT NULL AND resolved_at IS NOT NULL AND resolution IS NOT NULL)
        OR (status IN ('open','investigating') AND resolved_at IS NULL))
);
CREATE INDEX reports_queue ON reports (status, created_at, id);
CREATE INDEX reports_target ON reports (reported_squad_id, created_at DESC);
COMMENT ON TABLE reports IS '8. Alleged misconduct requiring human review; a report is not proof of an offense.';
CREATE TABLE report_evidence (
    report_id UUID NOT NULL REFERENCES reports(id),
    asset_id UUID NOT NULL REFERENCES media_assets(id),
    PRIMARY KEY (report_id, asset_id)
);
COMMENT ON TABLE report_evidence IS '8. Private attachments; check access before issuing signed object URLs.';
CREATE TABLE squad_verifications (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    squad_id UUID NOT NULL REFERENCES squads(id),
    submitted_by UUID NOT NULL REFERENCES users(id),
    requested_level_code VARCHAR(30) NOT NULL REFERENCES squad_levels(code),
    proof_type VARCHAR(100) NOT NULL,
    proof_asset_id UUID NOT NULL REFERENCES media_assets(id),
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','approved','rejected','revoked')),
    reviewed_by UUID REFERENCES users(id),
    reviewed_at TIMESTAMPTZ,
    decision_reason TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    version BIGINT NOT NULL DEFAULT 1 CHECK (version > 0),
    CHECK ((status = 'pending' AND reviewed_at IS NULL)
        OR (status <> 'pending' AND reviewed_by IS NOT NULL AND reviewed_at IS NOT NULL AND decision_reason IS NOT NULL))
);
CREATE UNIQUE INDEX verification_one_pending ON squad_verifications (squad_id) WHERE status = 'pending';
CREATE INDEX verifications_queue ON squad_verifications (status, created_at, id);
COMMENT ON TABLE squad_verifications IS '8. Squad-level proof and decision history. Approval updates squad level/verification in the same transaction.';
CREATE TABLE sanctions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    report_id UUID REFERENCES reports(id),
    squad_id UUID REFERENCES squads(id),
    user_id UUID REFERENCES users(id),
    action TEXT NOT NULL CHECK (action IN ('warning','suspension','ban')),
    reason TEXT NOT NULL,
    issued_by UUID NOT NULL REFERENCES users(id),
    starts_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    ends_at TIMESTAMPTZ,
    revoked_at TIMESTAMPTZ,
    revoked_by UUID REFERENCES users(id),
    CHECK ((squad_id IS NOT NULL AND user_id IS NULL) OR (squad_id IS NULL AND user_id IS NOT NULL)),
    CHECK (ends_at IS NULL OR ends_at > starts_at),
    CHECK ((revoked_at IS NULL) = (revoked_by IS NULL))
);
CREATE INDEX sanctions_squad ON sanctions (squad_id, starts_at);
CREATE INDEX sanctions_user ON sanctions (user_id, starts_at);
COMMENT ON TABLE sanctions IS '8. Warnings, suspensions and bans with expiry/revocation history; only authorized moderation commands create them.';

-- 9. ADMIN CONTENT AND AUDIT HISTORY
-- Under this section: landing content, promotional links, internal notes and change logs.
CREATE TABLE content_items (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    kind TEXT NOT NULL CHECK (kind IN ('event','video','advertisement','announcement','admin_note')),
    title VARCHAR(200) NOT NULL,
    body TEXT,
    target_url TEXT,
    asset_id UUID REFERENCES media_assets(id),
    audience TEXT NOT NULL DEFAULT 'public' CHECK (audience IN ('public','staff')),
    status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','published','archived')),
    starts_at TIMESTAMPTZ,
    ends_at TIMESTAMPTZ,
    display_order INTEGER NOT NULL DEFAULT 0,
    created_by UUID NOT NULL REFERENCES users(id),
    updated_by UUID NOT NULL REFERENCES users(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    version BIGINT NOT NULL DEFAULT 1 CHECK (version > 0),
    CHECK (ends_at IS NULL OR starts_at IS NULL OR ends_at > starts_at),
    CHECK (kind <> 'admin_note' OR audience = 'staff')
);
COMMENT ON TABLE content_items IS '9. Separate records for events, videos, ads and internal notes; avoids one wide row per landing-page layout.';
CREATE TABLE audit_log (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    actor_user_id UUID REFERENCES users(id),
    action VARCHAR(100) NOT NULL,
    entity_type VARCHAR(80) NOT NULL,
    entity_id UUID NOT NULL,
    correlation_id UUID NOT NULL,
    details JSONB NOT NULL DEFAULT '{}'::jsonb,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX audit_entity ON audit_log (entity_type, entity_id, occurred_at, id);
CREATE INDEX audit_time ON audit_log (occurred_at, id);
COMMENT ON TABLE audit_log IS '9. Append-only scrim/invite/staff history. Allowlisted details exclude secrets and raw private evidence.';

-- 10. EVENT DELIVERY AND REQUEST SAFETY
-- Under this section: reliable event delivery, retry-safe requests and event receipts.
CREATE TABLE request_receipts (
    actor_user_id UUID NOT NULL REFERENCES users(id),
    idempotency_key VARCHAR(150) NOT NULL,
    request_type VARCHAR(100) NOT NULL,
    request_hash CHAR(64) NOT NULL,
    response JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (actor_user_id, idempotency_key),
    CHECK (expires_at > created_at)
);
CREATE INDEX request_receipts_expiry ON request_receipts (expires_at);
COMMENT ON TABLE request_receipts IS '10. Completed request responses saved with changes; reject the same key with a different request.';
CREATE TABLE event_outbox (
    event_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    aggregate_type VARCHAR(80) NOT NULL,
    aggregate_id UUID NOT NULL,
    aggregate_version BIGINT NOT NULL CHECK (aggregate_version > 0),
    event_index SMALLINT NOT NULL DEFAULT 0 CHECK (event_index >= 0),
    event_type VARCHAR(120) NOT NULL,
    schema_version SMALLINT NOT NULL DEFAULT 1 CHECK (schema_version > 0),
    correlation_id UUID NOT NULL,
    causation_id UUID,
    payload JSONB NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    available_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    published_at TIMESTAMPTZ,
    attempts INTEGER NOT NULL DEFAULT 0 CHECK (attempts >= 0),
    lease_owner TEXT,
    lease_expires_at TIMESTAMPTZ,
    last_error TEXT,
    dead_lettered_at TIMESTAMPTZ,
    UNIQUE (aggregate_type, aggregate_id, aggregate_version, event_index)
);
CREATE INDEX outbox_pending ON event_outbox (available_at, occurred_at, event_id)
    WHERE published_at IS NULL AND dead_lettered_at IS NULL;
COMMENT ON TABLE event_outbox IS '10. Business changes/events commit together. Leased publisher retries with at-least-once delivery; not an event-sourcing store.';
COMMENT ON COLUMN event_outbox.event_index IS 'Multiple events can share one aggregate version; preserve order by version and event index.';
CREATE TABLE event_receipts (
    projection_name VARCHAR(100) NOT NULL,
    projection_generation INTEGER NOT NULL DEFAULT 1 CHECK (projection_generation > 0),
    event_id UUID NOT NULL,
    processed_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (projection_name, projection_generation, event_id)
);
COMMENT ON TABLE event_receipts IS '10. One receipt per event consumer, preventing duplicated event handling.';

-- 11A. DISPLAY VIEWS (DENORMALIZED)
-- Under this section: the UI reads names, labels, asset keys and calculated values,
-- not raw foreign-key IDs. These are presentation objects; entity tables stay 3NF.
CREATE OR REPLACE VIEW vw_squad_profile AS
SELECT
    s.id AS squad_id,
    s.public_number AS squad_number,
    s.name AS squad_name,
    s.slug AS squad_slug,
    s.acronym AS squad_acronym,
    s.bio AS squad_bio,
    s.status AS squad_status,
    s.verified_at IS NOT NULL AS is_verified,
    r.name AS region_name,
    r.code AS region_code,
    s.timezone,
    sl.name AS squad_level,
    owner.username AS owner_username,
    owner.display_name AS owner_display_name,
    coaching.primary_coach_name,
    COALESCE(coaching.coaches, '[]'::jsonb) AS coaches,
    avatar.object_key AS avatar_key,
    banner.object_key AS banner_key,
    COALESCE(roster.player_count, 0) AS player_count,
    COALESCE(roster.players, '[]'::jsonb) AS players,
    s.created_at,
    s.updated_at
FROM squads s
JOIN regions r ON r.code = s.region_code
JOIN squad_levels sl ON sl.code = s.level_code
JOIN users owner ON owner.id = s.owner_user_id
LEFT JOIN media_assets avatar ON avatar.id = s.avatar_asset_id
LEFT JOIN media_assets banner ON banner.id = s.banner_asset_id
LEFT JOIN LATERAL (
    SELECT
        max(COALESCE(u.display_name, u.username)) FILTER (WHERE c.is_primary) AS primary_coach_name,
        jsonb_agg(
            jsonb_build_object(
                'coachName', COALESCE(u.display_name, u.username),
                'coachRole', c.coach_role,
                'isPrimary', c.is_primary,
                'managesRoster', c.can_manage_roster,
                'managesScrims', c.can_manage_scrims
            ) ORDER BY c.is_primary DESC, c.coach_role, COALESCE(u.display_name, u.username)
        ) AS coaches
    FROM squad_coaches c
    JOIN users u ON u.id = c.user_id
    WHERE c.squad_id = s.id AND c.left_at IS NULL
) coaching ON true
LEFT JOIN LATERAL (
    SELECT
        count(*)::integer AS player_count,
        jsonb_agg(
            jsonb_build_object(
                'playerName', p.in_game_name,
                'rosterRole', sr.roster_role,
                'preferredRole', p.preferred_role,
                'currentRank', current_rank.name,
                'currentStars', p.current_stars,
                'highestRank', highest_rank.name,
                'highestStars', p.highest_stars,
                'avatarKey', player_avatar.object_key,
                'heroPool', COALESCE(hero_pool.heroes, '[]'::jsonb)
            ) ORDER BY CASE sr.roster_role WHEN 'captain' THEN 0 WHEN 'starter' THEN 1 ELSE 2 END,
                       p.in_game_name
        ) AS players
    FROM squad_roster sr
    JOIN players p ON p.id = sr.player_id
    LEFT JOIN game_ranks current_rank ON current_rank.id = p.current_rank_id
    LEFT JOIN game_ranks highest_rank ON highest_rank.id = p.highest_rank_id
    LEFT JOIN media_assets player_avatar ON player_avatar.id = p.avatar_asset_id
    LEFT JOIN LATERAL (
        SELECT jsonb_agg(h.name ORDER BY ph.preference_order) AS heroes
        FROM player_heroes ph
        JOIN heroes h ON h.id = ph.hero_id
        WHERE ph.player_id = p.id
    ) hero_pool ON true
    WHERE sr.squad_id = s.id AND sr.left_at IS NULL
) roster ON true;
COMMENT ON VIEW vw_squad_profile IS '11A. Display-ready squad profile. Foreign keys are resolved to names, asset keys and a public player roster.';

CREATE OR REPLACE VIEW vw_squad_schedule AS
SELECT
    s.id AS squad_id,
    s.public_number AS squad_number,
    s.name AS squad_name,
    opponent.id AS opponent_id,
    opponent.public_number AS opponent_number,
    opponent.name AS opponent_name,
    opponent.acronym AS opponent_acronym,
    opponent_avatar.object_key AS opponent_avatar_key,
    sc.id AS scrim_id,
    sc.scheduled_start,
    sc.scheduled_end,
    sc.series_format,
    sc.game_count,
    sc.status AS scrim_status,
    CASE WHEN sc.home_squad_id = s.id THEN result.home_wins ELSE result.away_wins END AS own_wins,
    CASE WHEN sc.home_squad_id = s.id THEN result.away_wins ELSE result.home_wins END AS opponent_wins,
    CASE
        WHEN result.outcome IS NULL THEN NULL
        WHEN result.outcome = 'void' THEN 'Void'
        WHEN result.outcome = 'draw' THEN 'Draw'
        WHEN (result.outcome = 'home_win' AND sc.home_squad_id = s.id)
          OR (result.outcome = 'away_win' AND sc.away_squad_id = s.id) THEN 'Win'
        ELSE 'Loss'
    END AS result_label,
    CASE
        WHEN result.home_wins IS NULL THEN NULL
        WHEN sc.home_squad_id = s.id THEN result.home_wins::text || '-' || result.away_wins::text
        ELSE result.away_wins::text || '-' || result.home_wins::text
    END AS score_display
FROM scrims sc
JOIN squads s ON s.id IN (sc.home_squad_id, sc.away_squad_id)
JOIN squads opponent ON opponent.id = CASE WHEN s.id = sc.home_squad_id THEN sc.away_squad_id ELSE sc.home_squad_id END
LEFT JOIN media_assets opponent_avatar ON opponent_avatar.id = opponent.avatar_asset_id
LEFT JOIN scrim_results result ON result.scrim_id = sc.id;
COMMENT ON VIEW vw_squad_schedule IS '11A. One readable schedule row per squad and scrim, with opponent details and display score.';

CREATE OR REPLACE VIEW vw_scrim_invites AS
SELECT
    i.id AS invite_id,
    'sent'::text AS invite_direction,
    sender.id AS squad_id,
    sender.name AS squad_name,
    recipient.id AS opponent_id,
    recipient.name AS opponent_name,
    recipient.acronym AS opponent_acronym,
    recipient_avatar.object_key AS opponent_avatar_key,
    COALESCE(creator.display_name, creator.username) AS sent_by_coach_name,
    coach.coach_role AS sent_by_coach_role,
    i.proposed_start,
    i.proposed_end,
    i.series_format,
    i.game_count,
    i.message,
    i.status,
    i.expires_at,
    i.created_at
FROM scrim_invites i
JOIN squads sender ON sender.id = i.sender_squad_id
JOIN squads recipient ON recipient.id = i.recipient_squad_id
JOIN users creator ON creator.id = i.created_by
JOIN squad_coaches coach ON coach.id = i.created_by_coach_id
LEFT JOIN media_assets recipient_avatar ON recipient_avatar.id = recipient.avatar_asset_id
UNION ALL
SELECT
    i.id, 'received', recipient.id, recipient.name, sender.id, sender.name, sender.acronym,
    sender_avatar.object_key, COALESCE(creator.display_name, creator.username), coach.coach_role, i.proposed_start, i.proposed_end,
    i.series_format, i.game_count, i.message, i.status, i.expires_at, i.created_at
FROM scrim_invites i
JOIN squads sender ON sender.id = i.sender_squad_id
JOIN squads recipient ON recipient.id = i.recipient_squad_id
JOIN users creator ON creator.id = i.created_by
JOIN squad_coaches coach ON coach.id = i.created_by_coach_id
LEFT JOIN media_assets sender_avatar ON sender_avatar.id = sender.avatar_asset_id;
COMMENT ON VIEW vw_scrim_invites IS '11A. Sent and received coach-to-coach invite cards with opponent roster owner, coach identity, branding and terms.';

CREATE OR REPLACE VIEW vw_messages AS
SELECT
    m.id AS message_id,
    m.conversation_id,
    m.sequence,
    sender_squad.name AS sender_squad_name,
    sender_squad.acronym AS sender_squad_acronym,
    COALESCE(sender_user.display_name, sender_user.username) AS sender_coach_name,
    sender_coach.coach_role AS sender_coach_role,
    recipient_squad.name AS recipient_squad_name,
    recipient_squad.acronym AS recipient_squad_acronym,
    m.body,
    m.created_at,
    m.deleted_at IS NOT NULL AS is_deleted
FROM messages m
JOIN conversations c ON c.id = m.conversation_id
JOIN squads sender_squad ON sender_squad.id = m.sender_squad_id
JOIN users sender_user ON sender_user.id = m.sender_user_id
JOIN squad_coaches sender_coach ON sender_coach.id = m.sender_coach_id
JOIN squads recipient_squad ON recipient_squad.id = CASE
    WHEN c.first_squad_id = m.sender_squad_id THEN c.second_squad_id ELSE c.first_squad_id END;
COMMENT ON VIEW vw_messages IS '11A. Coach-to-coach conversation display with sender and recipient squad names rather than IDs.';

CREATE OR REPLACE VIEW vw_notification_inbox AS
SELECT
    n.id AS notification_id,
    u.id AS user_id,
    COALESCE(u.display_name, u.username) AS recipient_name,
    s.name AS squad_name,
    n.kind,
    n.payload,
    n.read_at IS NOT NULL AS is_read,
    n.created_at
FROM notifications n
JOIN users u ON u.id = n.recipient_user_id
LEFT JOIN squads s ON s.id = n.recipient_squad_id;
COMMENT ON VIEW vw_notification_inbox IS '11A. Notification cards with recipient and squad names; payload remains action metadata.';

CREATE OR REPLACE VIEW vw_profile_feed AS
SELECT
    p.id AS post_id,
    s.id AS squad_id,
    s.name AS squad_name,
    s.acronym AS squad_acronym,
    avatar.object_key AS squad_avatar_key,
    COALESCE(author.display_name, author.username) AS author_name,
    p.body,
    p.label,
    p.visibility,
    COALESCE(attachments.assets, '[]'::jsonb) AS attachments,
    p.created_at,
    p.updated_at
FROM squad_posts p
JOIN squads s ON s.id = p.squad_id
JOIN users author ON author.id = p.author_user_id
LEFT JOIN media_assets avatar ON avatar.id = s.avatar_asset_id
LEFT JOIN LATERAL (
    SELECT jsonb_agg(jsonb_build_object('assetKey', a.object_key, 'mimeType', a.mime_type) ORDER BY pa.sort_order) AS assets
    FROM post_assets pa
    JOIN media_assets a ON a.id = pa.asset_id
    WHERE pa.post_id = p.id
) attachments ON true
WHERE p.deleted_at IS NULL;
COMMENT ON VIEW vw_profile_feed IS '11A. Display-ready profile feed including author name, squad branding and ordered attachment metadata.';

CREATE OR REPLACE VIEW vw_moderation_queue AS
SELECT
    'report'::text AS item_type, r.id AS item_id, reported.name AS subject_name,
    COALESCE(reporter.display_name, reporter.username) AS submitted_by_name,
    r.category, r.status, r.description AS summary, r.created_at AS submitted_at,
    COALESCE(assignee.display_name, assignee.username) AS assigned_to_name
FROM reports r
JOIN squads reported ON reported.id = r.reported_squad_id
JOIN users reporter ON reporter.id = r.reporter_user_id
LEFT JOIN users assignee ON assignee.id = r.assigned_to
UNION ALL
SELECT
    'feedback', f.id, COALESCE(s.name, 'Platform'), COALESCE(submitter.display_name, submitter.username),
    f.category, f.status, f.body, f.created_at, COALESCE(assignee.display_name, assignee.username)
FROM feedback f
JOIN users submitter ON submitter.id = f.submitted_by
LEFT JOIN squads s ON s.id = f.squad_id
LEFT JOIN users assignee ON assignee.id = f.assigned_to
UNION ALL
SELECT
    'verification', v.id, s.name, COALESCE(submitter.display_name, submitter.username),
    v.proof_type, v.status, level.name, v.created_at, COALESCE(reviewer.display_name, reviewer.username)
FROM squad_verifications v
JOIN squads s ON s.id = v.squad_id
JOIN users submitter ON submitter.id = v.submitted_by
JOIN squad_levels level ON level.code = v.requested_level_code
LEFT JOIN users reviewer ON reviewer.id = v.reviewed_by;
COMMENT ON VIEW vw_moderation_queue IS '11A. Staff queue that resolves IDs to subject, submitter, assignee and requested-level names.';

CREATE MATERIALIZED VIEW mv_squad_statistics AS
WITH series_outcomes AS (
    SELECT sc.home_squad_id AS squad_id, result.outcome,
           CASE WHEN result.outcome = 'home_win' THEN 1 ELSE 0 END AS wins,
           CASE WHEN result.outcome = 'away_win' THEN 1 ELSE 0 END AS losses,
           CASE WHEN result.outcome = 'draw' THEN 1 ELSE 0 END AS draws
    FROM scrims sc JOIN scrim_results result ON result.scrim_id = sc.id
    WHERE result.outcome <> 'void'
    UNION ALL
    SELECT sc.away_squad_id, result.outcome,
           CASE WHEN result.outcome = 'away_win' THEN 1 ELSE 0 END,
           CASE WHEN result.outcome = 'home_win' THEN 1 ELSE 0 END,
           CASE WHEN result.outcome = 'draw' THEN 1 ELSE 0 END
    FROM scrims sc JOIN scrim_results result ON result.scrim_id = sc.id
    WHERE result.outcome <> 'void'
)
SELECT
    s.id AS squad_id,
    s.public_number AS squad_number,
    s.name AS squad_name,
    s.acronym AS squad_acronym,
    level.name AS squad_level,
    region.name AS region_name,
    COALESCE(sum(o.wins), 0)::integer AS wins,
    COALESCE(sum(o.losses), 0)::integer AS losses,
    COALESCE(sum(o.draws), 0)::integer AS draws,
    count(o.squad_id)::integer AS completed_scrims,
    round(100.0 * COALESCE(sum(o.wins), 0) / NULLIF(count(o.squad_id), 0), 2) AS win_rate_percent
FROM squads s
JOIN squad_levels level ON level.code = s.level_code
JOIN regions region ON region.code = s.region_code
LEFT JOIN series_outcomes o ON o.squad_id = s.id
GROUP BY s.id, s.public_number, s.name, s.acronym, level.name, region.name;
CREATE UNIQUE INDEX mv_squad_statistics_pk ON mv_squad_statistics (squad_id);
COMMENT ON MATERIALIZED VIEW mv_squad_statistics IS '11A. Stored, denormalized squad totals for cards and profiles. Refresh after finalizing/correcting results.';

CREATE OR REPLACE VIEW vw_matchmaking_squads AS
SELECT
    profile.squad_id,
    profile.squad_number,
    profile.squad_name,
    profile.squad_acronym,
    profile.region_name,
    profile.squad_level,
    profile.is_verified,
    profile.avatar_key,
    profile.primary_coach_name,
    profile.coaches,
    profile.player_count,
    profile.players,
    statistics.wins,
    statistics.losses,
    statistics.draws,
    statistics.completed_scrims,
    statistics.win_rate_percent
FROM vw_squad_profile profile
LEFT JOIN mv_squad_statistics statistics ON statistics.squad_id = profile.squad_id
WHERE profile.squad_status = 'active';
COMMENT ON VIEW vw_matchmaking_squads IS '11A. Matchmaking cards: coach identity, complete current roster and readable squad statistics, with no raw relationship IDs required for display.';

CREATE MATERIALIZED VIEW mv_leaderboard AS
SELECT
    season.id AS season_id,
    season.name AS season_name,
    stats.squad_id,
    stats.squad_number,
    stats.squad_name,
    stats.squad_acronym,
    stats.squad_level,
    stats.region_name,
    rating.rating,
    stats.wins,
    stats.losses,
    stats.draws,
    stats.completed_scrims,
    stats.win_rate_percent,
    dense_rank() OVER (PARTITION BY season.id ORDER BY rating.rating DESC, stats.wins DESC, stats.squad_name) AS leaderboard_rank
FROM rating_seasons season
JOIN squad_ratings rating ON rating.season_id = season.id
JOIN mv_squad_statistics stats ON stats.squad_id = rating.squad_id;
CREATE UNIQUE INDEX mv_leaderboard_pk ON mv_leaderboard (season_id, squad_id);
CREATE INDEX mv_leaderboard_rank ON mv_leaderboard (season_id, leaderboard_rank);
COMMENT ON MATERIALIZED VIEW mv_leaderboard IS '11A. Stored leaderboard with squad names, rating, totals, win rate and rank. Refresh after rating/result changes.';

CREATE MATERIALIZED VIEW mv_admin_dashboard_metrics AS
SELECT 'active_squads'::text AS metric_name, count(*)::bigint AS metric_value FROM squads WHERE status = 'active'
UNION ALL SELECT 'open_reports', count(*)::bigint FROM reports WHERE status IN ('open', 'investigating')
UNION ALL SELECT 'pending_verifications', count(*)::bigint FROM squad_verifications WHERE status = 'pending'
UNION ALL SELECT 'scheduled_scrims', count(*)::bigint FROM scrims WHERE status IN ('scheduled', 'in_progress')
UNION ALL SELECT 'unread_notifications', count(*)::bigint FROM notifications WHERE read_at IS NULL;
CREATE UNIQUE INDEX mv_admin_dashboard_metrics_pk ON mv_admin_dashboard_metrics (metric_name);
COMMENT ON MATERIALIZED VIEW mv_admin_dashboard_metrics IS '11A. Stored admin dashboard counters. Refresh after relevant entity changes.';

-- 12. OPERATIONAL CONTRACT
-- Under this section: configure database roles with deployment-specific migrations.
-- display_api: SELECT only vw_* and mv_* objects; enforce public/member/staff access in API.
-- write_api: entity DML + event outbox/request receipt INSERT; no display-object writes.
-- refresh_worker: refresh mv_* objects after relevant events.
-- audit_log/rating_changes: application roles INSERT/SELECT only, never UPDATE/DELETE.
-- State machines, authorization and atomic event emission require application handlers.
COMMIT;
